testing_ctrl_portal/Models/CTRL_TestingContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace testing_ctrl_portal.Models
{
    public partial class CTRL_TestingContext : DbContext
    {
        public CTRL_TestingContext()
        {
        }

        public CTRL_TestingContext(DbContextOptions<CTRL_TestingContext> options)
            : base(options)
        {
        }

        public virtual DbSet<PasswordReset> PasswordReset { get; set; }
        public virtual DbSet<PersistCode> PersistCode { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("DefaultConnection");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PasswordReset>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Password).HasMaxLength(25);

                entity.Property(e => e.ResetCode)
                    .HasColumnName("Reset_code")
                    .HasMaxLength(25);

                entity.Property(e => e.ResetCodeSent).HasColumnName("Reset_code_sent");

                entity.Property(e => e.ResetCodeTimestamp)
                    .HasColumnName("Reset_code_timestamp")
                    .HasColumnType("datetime");

                entity.Property(e => e.UserEmail)
                    .HasColumnName("User_Email")
                    .HasMaxLength(100);

                entity.Property(e => e.UserName)
                    .HasColumnName("User_Name")
                    .HasMaxLength(100);
            });

            modelBuilder.Entity<PersistCode>(entity =>
            {
                entity.Property(e => e.Email).HasMaxLength(100);

                entity.Property(e => e.Expiration).HasColumnType("datetime");

                entity.Property(e => e.ResetCode).HasMaxLength(6);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

testing_ctrl_portal/Models/ErrorViewModel.cs
using System;

namespace testing_ctrl_portal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

testing_ctrl_portal/Models/PasswordReset.cs
using System;
using System.Collections.Generic;

namespace testing_ctrl_portal.Models
{
    public partial class PasswordReset
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string Password { get; set; }
        public bool? ResetCodeSent { get; set; }
        public DateTime? ResetCodeTimestamp { get; set; }
        public string ResetCode { get; set; }
    }
}

testing_ctrl_portal/Models/PersistCode.cs
using System;
using System.Collections.Generic;

namespace testing_ctrl_portal.Models
{
    public partial class PersistCode
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public DateTime? Expiration { get; set; }
        public string ResetCode { get; set; }
    }
}

testing_ctrl_portal/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using testing_ctrl_portal.Models;

namespace testing_ctrl_portal.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

testing_ctrl_portal/Controllers/UserFunctionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using testing_ctrl_portal.Models;

namespace testing_ctrl_portal.Controllers
{
    public class UserFunctionController : Controller
    {
        private readonly CTRL_TestingContext _db;
        public UserFunctionController(CTRL_TestingContext db)
        {
            _db = db;
            
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddUsername(PasswordReset p)
        {
            _db.PasswordReset.Add(p);
            _db.SaveChanges();
            return View("Index");
        }
        [HttpPost]
        public IActionResult ShowUsers()
        {
            List<PasswordReset> allUsers = _db.PasswordReset.ToList();
            return View(allUsers);
        }

        [HttpPost]
        public IActionResult SendCode()
        {
            int stringLength = 6;
            var stringBuilder = new StringBuilder();

            for (int i = 0; i < stringLength; i++)
            {
                Random random = new Random();
                string num = random.Next(0, 10).ToString();
                char alpha = (char)random.Next('a', 'z'); //if I make the set 'A', 'z' to try to incl. caps and lower, I get special char too
                if (random.Next() % 2 == 0)
                {
                    stringBuilder.Append(num);
                }
                else
                {
                    stringBuilder.Append(alpha);
                }
            }
            ViewBag.ResetCode = stringBuilder.ToString();

            return View("index");
        }
        [HttpPost]
        public IActionResult SaveCode(string email)
        {

            PersistCode entry = new PersistCode();
            entry.Email = email;
            entry.ResetCode = GetCode();
            entry.Expiration = DateTime.Now.AddMinutes(10);


            _db.PersistCode.Add(entry);
            _db.SaveChanges();

            ViewBag.Confirmation = $"your reset code has been sent to {email}";

            return View("index");
        }
        public static string GetCode()
        {
            int stringLength = 6;
            var stringBuilder = new StringBuilder();

            for (int i = 0; i < stringLength; i++)
            {
                Random random = new Random();
                string num = random.Next(0, 10).ToString();
                char alpha = (char)random.Next('a', 'z'); //if I make the set 'A', 'z' to try to incl. caps and lower, I get special char too
                if (random.Next() % 2 == 0)
                {
                    stringBuilder.Append(num);
                }
                else
                {
                    stringBuilder.Append(alpha);
                }
            }
           string code = stringBuilder.ToString();

            return code;
        }
        [HttpPost]
        public IActionResult ValidateCode(string code)
        {
            string response = "";

            List<PersistCode> validCode = _db.PersistCode.Where(x => x.ResetCode == code)
                                           .Where(x => x.Expiration > DateTime.Now).ToList();

            if (validCode.Count == 1)
            {
                response = "this code is valid for resetting your password";
            }    

            if (validCode.Count < 1)
            {
                response = "this code is no longer valid.  Please request a new one";

            }


            ViewBag.CodeResponse = $"{response}";


           
            return View("index");
        }
    }
}

testing_ctrl_portal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

testing_ctrl_portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - testing_ctrl_portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">testing_ctrl_portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserFunction" asp-action="Index">User functions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - testing_ctrl_portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

testing_ctrl_portal/Views/UserFunction/Index.cshtml
<h2>User Functions</h2>

@*testing to be sure I can view that entries to database have been recorded*@
<form asp-controller="UserFunction" asp-action="ShowUsers" method="post">
    <input type="submit" value="show all users" />
</form>

<hr>
@*testing writability to the database in this form block*@
<form asp-controller="UserFunction" asp-action="AddUsername" method="post">
    <label>Enter username:</label>
    <input type="text" name="UserName" />
    <br>
    <label>Enter email:</label>
    <input type="text" name="UserEmail" />
    <br>
    <label>Enter password:</label>
    <input type="text" name="Password" />
    <br>
    <label>Has reset code been sent?:</label>
    <input type="radio" id="true" name="ResetCodeSent" value="true" />
    <label for="true">true</label>
    <input type="radio" id="false" name="ResetCodeSent" value="false" />
    <label for="false">false</label>
    <br>
    <label>Current time:</label>
    <input type="text" name="ResetCodeTimestamp" value="@DateTime.Now" />
    <br>
    <label>Enter ResetCode:</label>
    <input type="text" name="ResetCode" />
    <br>
    <input type="submit">

</form>
<hr>

@*testing ability to generate 6 digit alphanumeric code on demand*@
<form asp-action="SendCode" asp-controller="UserFunction" method="post">
    <label>Click here to get a reset code:</label>
    <input type="submit" value="show me a code" />

</form>

<p>@ViewBag.Resetcode</p>

<hr>

@*Write code to databse*@
<form asp-action="SaveCode" asp-controller="UserFunction" method="post">
    <p>Need a password reset code?  Enter your email below and click submit</p>
    <input type="text" name="email" />
    <input type="submit" />

</form>
<p>@ViewBag.Confirmation</p>

@*check to see if reset code is valid to proceed with password reset*@

<form asp-action="validateCode" asp-controller="userfunction" method="post">
    <p>enter the code you received here to proceed with resetting your password:</p>
    <input type="text" name="code" />
    <input type="submit" />

</form>
<p>@ViewBag.CodeResponse</p>

testing_ctrl_portal/Views/UserFunction/ShowUsers.cshtml
@model List<PasswordReset>

@foreach (PasswordReset p in Model)
{
    <p>@p.Id</p>
    <p>@p.UserName</p>
    <p>@p.UserEmail</p>
    <hr>
}